version: '2.1'
volumes:
  waarp-site2-dblog:
  waarp-site2-etc:
  waarp-site2-log:
  waarp-site2-data:
  waarp-site2-db:
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: waarp-site2
      POSTGRES_PASSWORD: V3ry1nS3cur3P4ssw0rd
      POSTGRES_USER: waarp
    volumes:
    - waarp-site2-db:/var/lib/postgresql/data
    - waarp-site2-dblog:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  waarp-r66:
    build: ./
    image: fjudith/waarp-r66:3.0.9
    environment:
      WAARP_ADMIN_PASSWORD: V3ry1nS3cur3P4ssw0rd
      WAARP_APPNAME: site2
      WAARP_DATABASE_TYPE: postgresql
      WAARP_DATABASE_HOST: postgres
      WAARP_DATABASE_USERNAME: waarp
      WAARP_DATABASE_PASSWORD: V3ry1nS3cur3P4ssw0rd
      WAARP_DATABASE_NAME: waarp-site2
    volumes:
    - waarp-site2-etc:/etc/waarp
    - waarp-site2-data:/var/lib/waarp
    - waarp-site2-log:/var/log/waarp
    depends_on:
      postgres:
        condition: service_healthy
    ports:
    - 6676:6666/tcp
    - 6677:6667/tcp
    - 8076:8066/tcp
    - 8077:8067/tcp
    - 8078:8088/tcp
