apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-r66-pg
    app: waarp-r66
  name: waarp-r66-pg
spec:
  ports:
  - name: "postgres"
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: waarp-r66-pg
    app: waarp-r66
    tiers: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-db
    app: waarp-r66
  name: waarp-site1-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      io.kompose.service: waarp-site1-db
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-dblog
    app: waarp-r66
  name: waarp-site1-dblog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      io.kompose.service: waarp-site1-dblog
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: waarp-r66-pg
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: waarp-r66-pg
        app: waarp-r66
    spec:
      containers:
      - image: postgres
        name: waarp-r66-pg
        env:
        - name: POSTGRES_DB
          value: site1-waarp
        - name: POSTGRES_USER
          value: waarp
        # $ kubectl create secret generic postgres-pass --from-file=postgres.password.txt
        # make sure postgres.password.txt does not have a trailing newline
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: postgres.password.txt
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: waarp-site1-db
          subPath: db
        - mountPath: /var/log/postgresql
          name: waarp-site1-dblog
          subPath: dblog
      volumes:
      - name: waarp-site1-db
        persistentVolumeClaim:
          claimName: waarp-site1-db
      - name: waarp-site1-dblog
        persistentVolumeClaim:
          claimName: waarp-site1-dblog
status: {}
