apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-r66-pg
  name: waarp-r66-pg
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: waarp-r66-pg
status:
  loadBalancer: {}
