apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-etc
    type: local
  name: waarp-site1-etc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/media/waarp-site1-etc"
status: {}
