apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-data
    type: local
  name: waarp-site1-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/var/lib/docker/volumes/waarp-site1-data"
status: {}
