apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-db
    type: local
  name: waarp-site1-db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/var/lib/kubernetes/pv/waarp-site1-db"
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-dblog
    type: local
  name: waarp-site1-dblog
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/var/lib/kubernetes/pv/waarp-site1-dblog"
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-etc
    type: local
  name: waarp-site1-etc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/var/lib/kubernetes/pv/waarp-site1-etc"
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-data
    type: local
  name: waarp-site1-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/var/lib/kubernetes/pv/waarp-site1-data"
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-site1-log
    type: local
  name: waarp-site1-log
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/var/lib/kubernetes/pv/waarp-site1-log"
status: {}
