apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-cifs
  name: waarp-cifs
spec:
  ports:
  - name: "137"
    port: 137
    targetPort: 137
  - name: "137"
    port: 137
    protocol: UDP
    targetPort: 137
  - name: "138"
    port: 138
    targetPort: 138
  - name: "138"
    port: 138
    protocol: UDP
    targetPort: 138
  - name: "139"
    port: 139
    targetPort: 139
  - name: "445"
    port: 445
    targetPort: 445
  - name: "445"
    port: 445
    protocol: UDP
    targetPort: 445
  selector:
    io.kompose.service: waarp-cifs
status:
  loadBalancer: {}
