apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-r66
  name: waarp-r66
spec:
  ports:
  - name: "6666"
    port: 6666
    targetPort: 6666
  - name: "6667"
    port: 6667
    targetPort: 6667
  - name: "8066"
    port: 8066
    targetPort: 8066
  - name: "8067"
    port: 8067
    targetPort: 8067
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.kompose.service: waarp-r66
status:
  loadBalancer: {}
